version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nurabi12
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
